lbs:
  fedora:
    '21':
      repos: ['http://download.mono-project.com/repo/centos/']
  centos:
    '6':
      repos: ['http://download.mono-project.com/repo/centos/']
    '7':
      repos: ['http://download.mono-project.com/repo/centos/']
